#!/bin/bash

#SBATCH --job-name=global_w5e5_extract
#SBATCH -A node
#SBATCH -p node
#SBATCH --chdir=/home/harichan/
#SBATCH --qos normal
#SBATCH --mail-user=chantal.hari@wsl.ch
#SBATCH --mail-type==SUBMIT,END,FAIL
#SBATCH -o logs/global_w5e5_extract%j.out
#SBATCH -e logs/global_w5e5_extract%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --mem-per-cpu=3G
#SBATCH --time=00:10:00

STARTDATE=2010-12-31
YEAR=$(date -d "$STARTDATE $SLURM_ARRAY_TASK_ID days" +%Y)
MONTH=$(date -d "$STARTDATE $SLURM_ARRAY_TASK_ID days" +%m)
DAY=$(date -d "$STARTDATE $SLURM_ARRAY_TASK_ID days" +%d)


singularity exec -B /storage /home/harichan/singularity/harichans.sing R --vanilla -f /home/harichan/scripts/chelsa_w5e5-validation/chelsa_w5e5_validation/functions/extract_w5e5_global.R --args ${YEAR} ${MONTH} ${DAY}


